### ISSUE TITLE
Typo in "Recipes with rsample" vignette

### ISSUE THREAD

**Issue by tmastny** [topepo/rsample#26]
Hi,

I accidentally posted this in the recipes repo before I realized this was an `rsample` vignette:
https://github.com/topepo/recipes/issues/98

The problem is in this vignette:

https://cran.r-project.org/web/packages/rsample/vignettes/Recipes_and_rsample.html

Right before the "Working with Resamples" section there is this sentence:

>The next section will explore recipes using bootstrap resampling is used for modeling:

I believe they mean

>The next section will explore recipes when bootstrap resampling is used for modeling:

or

>The next section will explore recipes using bootstrap resampling for modeling:

**Comment by topepo** [comment]
Got it. Thanks
