### ISSUE TITLE
issues when loading a rsample tibble with rdata

### ISSUE THREAD

**Issue by csetraynor** [topepo/rsample#36]
Hi,

 I know this isn't the great contribution, but I wanted to report a ("bug") problem I found when loading a big dataset. My dataset has 86 rows and 7000 columns (gene expression dataset) and when I wanted to save my environment and loading it again I found out the memory limit of my CPU (32 GB Windows 10 currently) was going overflowed. I understand that this is because rsample is using a memory-efficient storage of large data when working but when loading this isn't working because R needs to read each dataset before?...  
I was using the classic commands:
save from Rstudio Environment option
load(my_env.Rdata)

Error message (classic):
Memory Allocation “Error: cannot allocate vector of size 75.1 Mb”

I already increased memory.limit, checked the CPU Performance.

carlos,

**Comment by csetraynor** [comment]
I just want to comment that I closed the issue because I understand is probably not the place to ask this. Just to add, that I solved the problem by saving each model and measurements and cleaning the workspace and fitting a new model obtaining the measures and cleaning and so on...
This is just being a bit more clever than I was when asking...

**Comment by topepo** [comment]
Thanks for the comment. This is very helpful. 

This is a big issue and one that I think is impossible to get around. `caret` doesn't save the intermediate models for this exact reason. I think that it will be people's expectation (that they should save the models) and it can be surprising how much space some of the models occupy.
