### ISSUE TITLE
rset constructor

### ISSUE THREAD

**Issue by hadley** [topepo/rsample#6]
I think you should have something like this:

```R
new_rset <- function(splits, ..., subclass = character()) {
  stopifnot(is.list(splits))

  structure(list(
    splits = splits,
    ...
  ), class = c(subclass, "rset"))
}
```

That's also a good place to document the details of the object structure.

**Comment by topepo** [comment]
> Maybe the `print()` method should display the splits too? (i.e. `print(x$splits)`)

Maybe it's been a while since I looked at this note but right now it does:
```r
> vfold_cv(mtcars)
# 10-fold cross-validation 
# A tibble: 10 x 2
         splits     id
         <list>  <chr>
 1 <S3: rsplit> Fold01
 2 <S3: rsplit> Fold02
 3 <S3: rsplit> Fold03
 4 <S3: rsplit> Fold04
 5 <S3: rsplit> Fold05
 6 <S3: rsplit> Fold06
 7 <S3: rsplit> Fold07
 8 <S3: rsplit> Fold08
 9 <S3: rsplit> Fold09
10 <S3: rsplit> Fold10
```
Does the function `obj_sum` change how the objects are shown in the tibble (i.e. instead of showing "`<S3: rsplit>`")?

**Comment by topepo** [comment]
`new_rset` was added as the constructor function.
